// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repos.Data;

#nullable disable

namespace repos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610131902_AtualizaMetaGuilherme")]
    partial class AtualizaMetaGuilherme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("repos.Data.ColaboradorMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFinalContrato")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicialContrato")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MetaS1")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MetaS2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MetaS3")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MetaS4")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NomeColaborador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("RecuperadoS1")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RecuperadoS2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RecuperadoS3")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RecuperadoS4")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("ColaboradoresMetas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataFinalContrato = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicialContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaS1 = 6000m,
                            MetaS2 = 6000m,
                            MetaS3 = 6000m,
                            MetaS4 = 6000m,
                            NomeColaborador = "BEN HUR MAIA DE ALMEIDA",
                            RecuperadoS1 = 4208m,
                            RecuperadoS2 = 0m,
                            RecuperadoS3 = 0m,
                            RecuperadoS4 = 0m
                        },
                        new
                        {
                            Id = 2,
                            DataFinalContrato = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicialContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaS1 = 6000m,
                            MetaS2 = 6000m,
                            MetaS3 = 6000m,
                            MetaS4 = 6000m,
                            NomeColaborador = "DAVI DE OLIVEIRA MELO",
                            RecuperadoS1 = 3752m,
                            RecuperadoS2 = 0m,
                            RecuperadoS3 = 0m,
                            RecuperadoS4 = 0m
                        },
                        new
                        {
                            Id = 3,
                            DataFinalContrato = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicialContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaS1 = 6000m,
                            MetaS2 = 6000m,
                            MetaS3 = 6000m,
                            MetaS4 = 6000m,
                            NomeColaborador = "GUILHERME NASCIMENTO",
                            RecuperadoS1 = 7308m,
                            RecuperadoS2 = 0m,
                            RecuperadoS3 = 0m,
                            RecuperadoS4 = 0m
                        },
                        new
                        {
                            Id = 4,
                            DataFinalContrato = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicialContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaS1 = 6000m,
                            MetaS2 = 6000m,
                            MetaS3 = 6000m,
                            MetaS4 = 6000m,
                            NomeColaborador = "Ana Luisa",
                            RecuperadoS1 = 3666m,
                            RecuperadoS2 = 0m,
                            RecuperadoS3 = 0m,
                            RecuperadoS4 = 0m
                        },
                        new
                        {
                            Id = 5,
                            DataFinalContrato = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicialContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaS1 = 6000m,
                            MetaS2 = 6000m,
                            MetaS3 = 6000m,
                            MetaS4 = 6000m,
                            NomeColaborador = "GUILHERME SOARES",
                            RecuperadoS1 = 1079m,
                            RecuperadoS2 = 0m,
                            RecuperadoS3 = 0m,
                            RecuperadoS4 = 0m
                        },
                        new
                        {
                            Id = 6,
                            DataFinalContrato = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicialContrato = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetaS1 = 6000m,
                            MetaS2 = 6000m,
                            MetaS3 = 6000m,
                            MetaS4 = 6000m,
                            NomeColaborador = "VICTORIA",
                            RecuperadoS1 = 2111m,
                            RecuperadoS2 = 0m,
                            RecuperadoS3 = 0m,
                            RecuperadoS4 = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
