// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repos.Data;

#nullable disable

namespace repos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605123615_SeedColaboradores")]
    partial class SeedColaboradores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("repos.Data.MetaCobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeColaborador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorAtingido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorMeta")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("MetasCobranca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeColaborador = "Guilherme",
                            ValorAtingido = 0m,
                            ValorMeta = 10000m
                        },
                        new
                        {
                            Id = 2,
                            NomeColaborador = "Davi",
                            ValorAtingido = 0m,
                            ValorMeta = 10000m
                        },
                        new
                        {
                            Id = 3,
                            NomeColaborador = "Ben",
                            ValorAtingido = 0m,
                            ValorMeta = 10000m
                        },
                        new
                        {
                            Id = 4,
                            NomeColaborador = "Pamela",
                            ValorAtingido = 0m,
                            ValorMeta = 10000m
                        },
                        new
                        {
                            Id = 5,
                            NomeColaborador = "Vitoria",
                            ValorAtingido = 0m,
                            ValorMeta = 10000m
                        },
                        new
                        {
                            Id = 6,
                            NomeColaborador = "Ana",
                            ValorAtingido = 0m,
                            ValorMeta = 10000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
